export const SORT_BY_SUGGEST = 'SORT_BY_SUGGEST';
export const SORT_BY_PRICE_UP = 'SORT_BY_PRICE_UP';
export const SORT_BY_PRICE_DOWN = 'SORT_BY_PRICE_DOWN';
export const SORT_BY_RANKING = 'SORT_BY_RANKING';
export const SORT_BY_PROMOTE = 'SORT_BY_PROMOTE';